# Project: Project69
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"S:/DevCpp/Dev-Cpp/TDM-GCC-64/lib" -L"S:/DevCpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"S:/DevCpp/Dev-Cpp/TDM-GCC-64/include" -I"S:/DevCpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"S:/DevCpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"S:/DevCpp/Dev-Cpp/TDM-GCC-64/include" -I"S:/DevCpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"S:/DevCpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"S:/DevCpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Project69.exe
CXXFLAGS = $(CXXINCS) -ansi
CFLAGS   = $(INCS) -ansi
DEL      = S:\DevCpp\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
